### ISSUE TITLE
Section Backrounds

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/stewart#11]
Colors
Images

**Comment by badvision** [comment]
There are some additional variants for shading under text blocks that have some transparency (e.g. 20% opaque black) and other variants for different font colors in various parts of the about us pages, among other places.

**Comment by badvision** [comment]
Currently if the section has the style "image" then the first image should be a background image that covers the whole section.

**Comment by shsteimer** [comment]
I think this is done, closing for now, can open separate issues if we find other backgrounds we need to handle
