### ISSUE TITLE
Table block not rendering when there are no content rows

### ISSUE THREAD

**Issue by fperez-leappoint** [hlxsites/stewart#111]
This is an issue with the table block. When only the header row exists and no rows below that, the block doesn't render.

This is a content issue, tables with no content are not good. But the current site renders the empty table. Sample:

<img width="1377" alt="live site" src="https://github.com/hlxsites/stewart/assets/89093701/5f85ea7c-7714-424a-8d0f-9b227216be70">

block:

<img width="1350" alt="table block" src="https://github.com/hlxsites/stewart/assets/89093701/bcab3442-7b7a-4837-a57f-4dfc1fe145e9">

**Comment by badvision** [comment]
Checking the markdown version, the table content makes it out of word intact [1] so it makes sense to examine this as a possible code issue.  I'll look into it.

[1] https://main--stewart--hlxsites.hlx.page/en/education-and-training/sureclose-advantage.md
