### ISSUE TITLE
Account for additional variations of list

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/stewart#133]
3 col
fluid 
1 col

see importer results and fgrep for places these appear

**Comment by badvision** [comment]
Fluid:
- [/en/about-stewart/sustainability/culture-of-caring](https://main--stewart--hlxsites.hlx.live/en/about-stewart/sustainability/culture-of-caring)
- [/en/news](https://main--stewart--hlxsites.hlx.live/en/news)
- [/en/insights](https://main--stewart--hlxsites.hlx.live/en/insights)

1 Column:
- [/en/customer-type/commercial-title-closing-services/underwriting-services](https://main--stewart--hlxsites.hlx.live/en/customer-type/commercial-title-closing-services/underwriting-services)
- [/en/fragments/list/customer-type-commercial-title-closing-services-2](https://main--stewart--hlxsites.hlx.live/en/fragments/list/customer-type-commercial-title-closing-services-2)
- [/en/fragments/list/customer-type-customer-type-3](https://main--stewart--hlxsites.hlx.live/en/fragments/list/customer-type-customer-type-3)
- [/en/fragments/list/customer-type-title-and-closing-services-1](https://main--stewart--hlxsites.hlx.live/en/fragments/list/customer-type-title-and-closing-services-1)
- [/en/about-stewart/stewart-companies](https://main--stewart--hlxsites.hlx.live/en/about-stewart/stewart-companies)

3 Column:
- [](https://main--stewart--hlxsites.hlx.live)
- [](https://main--stewart--hlxsites.hlx.live)
- [](https://main--stewart--hlxsites.hlx.live)
