### ISSUE TITLE
Ask-us page display issues with form

### ISSUE THREAD

**Issue by badvision** [hlxsites/stewart#134]
Ask us (ask-us-ny) form works but the landing page it is on hides it because of some hero logic issues.  Currently the landing pages are not present, but https://fom-gen--stewart--hlxsites.hlx.page/en/landing-pages/trd-ron will need to be manually authored to resolve any display issues with the form.  The form used on this page should be "Ask us NY" (it is case-insensitive)

**Comment by shsteimer** [comment]
@badvision what's the status of this? is this good to go with what I did for landing pages?

**Comment by badvision** [comment]
Yeah we can close.  Re-open as needed later.
