### ISSUE TITLE
Use clustering for bing maps integration in office locator

### ISSUE THREAD

**Issue by usman-khalid** [hlxsites/stewart#148]
To avoid taking a performance hit, it would be neat if we could look into clustering for bing map markers (pushpins). If there are a lot of them, we should ideally cluster them to avoid making a bunch of requests and instead have the user zoom in to get more granular.

Basic clustering example: https://learn.microsoft.com/en-us/bingmaps/v8-web-control/map-control-concepts/clustering-module-examples/basic-clustering-example

**Comment by shsteimer** [comment]
sounds like a good idea.
