### ISSUE TITLE
Column block - Carousel variant

### ISSUE THREAD

**Issue by badvision** [hlxsites/stewart#18]
If a column has a carousel variant, that means one of the columns is a stack of images that should be auto-blocked into a carousel.  There are a few instances of this on the careers page.

![image](https://github.com/hlxsites/stewart/assets/5144198/434f8ec7-a674-41ce-ab39-26eb9d9a2c64)

- https://www.stewart.com/en/about-stewart/careers.html

**Comment by shsteimer** [comment]
depends on #16
