### ISSUE TITLE
List content

### ISSUE THREAD

**Issue by badvision** [hlxsites/stewart#19]
Many pages in AEM use a Generic List component in two different ways:
Variant 1: A two-column layout with icon + links or icon + text, this is on the homepage and a text variant is on the careers page

![image](https://github.com/hlxsites/stewart/assets/5144198/7c36362b-2304-46dd-82cb-6dffefcfaf02)

![image](https://github.com/hlxsites/stewart/assets/5144198/ccc48c24-7685-48f8-8e25-b8419998502a)

Variant 2: Text-only (no icons) -- this is also on the Careers page
![image](https://github.com/hlxsites/stewart/assets/5144198/50d9d9c5-4ebb-4f2d-bb83-2327dadeb790)

There is a variant called "2 col" for two-columns in desktop view but we might need to see if there is even such a thing as a 1 column variant before implementing that -- it might make more sense to generally assume 2-column is the default behavior.

- https://www.stewart.com/en.html
- https://www.stewart.com/en/about-stewart/careers.html

**Comment by shsteimer** [comment]
I kind of think this can be a single block, no variants, unless, as you indicate, we need to let the author choose to layout 2 columns, vs. 1 col.

If the author wants icons, they create a 2 column table, and put the icons in the first column.
if no icons, they make it a 1 columns table and just add the text. the code will lay it out as 2 columns, splitting the items evenly between the 2 cols.

question on icons. are those from font awesome? or are they images?
