### ISSUE TITLE
Forms content not working properly

### ISSUE THREAD

**Issue by badvision** [hlxsites/stewart#21]
This is a placeholder to discover forms that appear across the site and create additional stories as needed to address those forms.  Acceptance criteria are only the identification of those forms and creating stories for them.

Examples:
- Find us form on homepage 
![image](https://github.com/hlxsites/stewart/assets/5144198/fc1442dc-14cf-47c0-bbd5-cbfef0bab269)

Several forms in the contact section of the site such as:
- https://www.stewart.com/en.html
- https://www.stewart.com/en/about-stewart/supplier-diversity-at-stewart.html
- https://www.stewart.com/en/agent-verification.html
- https://www.stewart.com/en/contact-us/contact-customer-relations.html
- https://www.stewart.com/en/contact-us/contact-information-technology-security.html
- https://www.stewart.com/en/contact-us/customer-service-inquiries-and-complaints.html
- https://www.stewart.com/en/contact-us/submit-a-claim.html
- https://www.stewart.com/en/contact-us/submit-a-claim1.html
- https://www.stewart.com/en/cpl-form.html
- https://www.stewart.com/en/deed-documentary-stamps.html

**Comment by shsteimer** [comment]
There are also quite a few under quick links as well.

**Comment by arcreddy** [comment]
[Stewart - Forms List.xlsx](https://github.com/hlxsites/stewart/files/12232497/Stewart.-.Forms.List.xlsx)

**Comment by shsteimer** [comment]
superseded by other forms issues.
