### ISSUE TITLE
Style System to Section Style/Block Variant mapping

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/stewart#33]
See https://adobe-dx-support.slack.com/archives/C04S4UZRW8J/p1689721947961679

Issues to be looked at later once more of site is built out:
* ss-margin-ss and  ss-margin-bottom-small on sections
* opacity levels, both for sections with background images and heroes

**Comment by badvision** [comment]
most heros use `ss-backgroundbrightness-dark` so instead that was assumed as the default (unspecified) style for hero, and other heros that do not use dark have a `light` style instead.
