### ISSUE TITLE
Hero - Narrow content use cases

### ISSUE THREAD

**Issue by arcreddy** [hlxsites/stewart#39]
Below are the possible use cases for narrow content.

col-xl-7 col-lg-11 col-md-7 - https://www.stewart.com/en.html
col-md-7 col-lg-9 - https://www.stewart.com/en/customer-type/title-agents.html
col-md-7 col-lg-11 col-xl-7 - https://www.stewart.com/en/customer-type/lender-title-settlement-services/mortgage-originations/appraisal-and-valuations.html
col-md-6 col-lg-8 - https://www.stewart.com/en/locate-an-office.html

**Comment by badvision** [comment]
Should all of the heroes in this case have the same style added (narrow) or do we need different styles?

**Comment by arcreddy** [comment]
No, the Content is narrow only on the pages mentioned above. It is full-width otherwise.
