### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/stewart#4]
<img width="1577" alt="Screenshot 2023-07-12 at 11 24 57 AM" src="https://github.com/hlxsites/stewart/assets/1646396/6758458f-2feb-4cde-9e76-3ad650366397">

Should be auto-blocks per Franklin standard

**Comment by badvision** [comment]
Importer respects the content for image and headers, there might be some places where other content might appear too such as the Careers page.
