### ISSUE TITLE
AEM Asset Integration

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/stewart#59]
need to determine how we integrate with AEM Assets. this includes both links to assets such as PDFs, and author selection of assets.

some options:
* move to franklin
* keep /content/dam alive and route at cdn

**Comment by badvision** [comment]
I believe they should stay in the DAM and we should explore how to improve the authoring experience for DAM-hosted content.

**Comment by badvision** [comment]
For legacy AEM Asset (On-prem and/or AMS-hosted 6.5) the best option is probably using Asset Selector: https://experienceleague.adobe.com/docs/experience-manager-65/assets/managing/asset-selector.html?lang=en
This integration would not work with AEM CS, and therefore it is worth noting that for AEM CS (including Asset Essentials) the better option is the Micro-frontend Asset Selector: https://github.com/adobe/aem-assets-selectors-mfe-examples

**Comment by badvision** [comment]
Other considerations for this include the overall authoring workflow including assets (approvals, publish, etc) and also CDN integration for Franklin vs. published AEM Assets content.
