### ISSUE TITLE
Tables inside of Accordions

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/stewart#60]
See https://www.stewart.com/en/education-and-training/sureclose-advantage.html

Relates to #58  and #12 

probably will require modifying the accordion block to use multiple sections or something

**Comment by fperez-leappoint** [comment]
I'll be grabbing this one. Does seem necessary to use sections but let's discuss

**Comment by shsteimer** [comment]
@fperez-leappoint There's probably a number of ways this could be done. I think the easiest may be that the accordion is all in one section. In the section, h2's become the accordion headers, and any content between the h2's including blocks, become the content of the panels. the section then gets a metadata applied of Style=Accordion, and we use that during auto blocking code to make it happen.

I did something similar here https://github.com/hlxsites/elixirsolutions/blob/main/scripts/scripts.js#L260 that you can use as a starting point.

we'll also need to update the importer.

**Comment by badvision** [comment]
I'm importing the table block for #58 -- I don't know if it's really necessary to reuse it but I thought I'd let you know in case that is helpful information.  See the "table" branch for updates.
